### ISSUE TITLE
Avoid n+1 network requests with embedded reference collections

### ISSUE THREAD

**Issue by carlobeltrame** [ecamp/hal-json-vuex#7]
Use case brought up by @simfeld.

Say my application loads some `user`, and then continues to display the `chapters` of the `lastReadBook` of said `user`. Assume also that the user is always loaded first, because of some plausibility checks. This could look something like this:
```html
<!-- template part of the Vue component -->
<li v-for="chapter in user().lastReadBook().chapters().items">...</li>
```
```js
// script part of the same Vue component
props: {
  user: { type: Function, required: true }
}
```

Now, assume that the API sends the data of the `user`, with embedded `lastReadBook`, which has embedded the `chapters`, but the API decided for some reason to only send the chapters as references (which we support):
```js
{
  username: 'john',
  _links: { self: { href: '/users/333' } },
  _embedded: {
    lastReadBook: {
      name: 'The last book you\'ll ever read',
      _links: { self: { href: '/books/3' } },
      _embedded: {
        chapters: [
          { _links: { self: '/chapters/1028' } },
          { _links: { self: '/chapters/1031' } },
          { _links: { self: '/chapters/1037' } },
          { _links: { self: '/chapters/1038' } }
        ]
      }
    }
  }
}
```

**Proposed behaviour**
When accessing the `items` of `lastReadBook`, the store is smart enough to load the data for all chapters in one additional network call to `/books/3`.

**Current behaviour**
Each chapter is loaded in a separate network request.

**Comment by usu** [comment]
> **Proposed behaviour**
> When accessing the `items` of `lastReadBook`, the store is smart enough to load the data for all chapters in one additional network call to `/books/3`.

Not sure I understand 100%. In your scenario, you assume that `/books/3` embeds the chapters as full objects and not only as links and that's how you save network requests?

**Comment by carlobeltrame** [comment]
Yes, by reloading the closest parent of the collection that has an own self link (and is therefore reloadable), I hope to get the data from the API. In case the API still doesn't give the full data (we have that case in ecamp with the camp collaborations on the camp admin page), it falls back to loading each entry sequentially.

**Comment by usu** [comment]
Ok, I see. I tried to look at the code was not immediately clear if I understood how it's all connected.

In essence, when I access 
`user().lastReadBook().chapters().items[0]`
you detect that this item is not in the store. You also detect that that `user().lastReadBook()` has never been loaded individually. So you load `lastReadBook`, wait for it to finish. Then `user().lastReadBook().chapters().items[0]` is accessed. If it's still not in the store, you load the chapter separately. Correct?

Generally, I believe it should be the frontend's developer to make smart API requests to limit the number of network requests (as you also did in https://github.com/ecamp/ecamp3/pull/693/files). But if it helps to reduce requests automatically without drawback, good for me.

Worst case scenario is that I have to wait for 1 additional unnecessary network request, correct?

I'm not sure if I would have taken the same config name `avoidNPlusOneRequests`, though. Something a long the line of `embeddedCollections.forceParentPreload` would have been more intuitive to me, describing more precisely the behavior instead of the intention. But that's of course very subjective.

**Comment by carlobeltrame** [comment]
Yes, your description is almost correct. Except that the check already happens when you access `user().lastReadBook().chapters().items`, and at that point it checks whether all of the items have at least started loading from the API. If at least one of them is still unknown in the store (i.e. it hasn't been loaded and hasn't started loading either), the whole collection is (re-)loaded in a single network request, in the case of embedded collections that would mean the parent entity `lastReadBook` is reloaded.

About the naming, not so sure, because the fix also applies to normal collections (i.e. entities that come with an `items` array from the API), even though in ecamp we don't have a use case for this scenario (yet).
